
//import static SelectCar.temp;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pratik rathod
 */
public class BookVehicle extends javax.swing.JFrame {

    /**
     * Creates new form BookVehicle
     */
    public static String temp;
    public BookVehicle() {
        initComponents();
        //frm.setDateFormatString("yyyy-MM-dd");
    }
     public BookVehicle(String para) {
        initComponents();
        temp=para;
        ema.setText(temp);
        ema.setEditable(false);
                 ema.setEnabled(false);
                 
        //frm.setDateFormatString("yyyy-MM-dd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pic = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        drp = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ema = new javax.swing.JTextField();
        frm = new com.toedter.calendar.JDateChooser();
        to1 = new com.toedter.calendar.JDateChooser();
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(date,null,null,Calendar.HOUR_OF_DAY);
        jSpinner1 = new javax.swing.JSpinner(sm);
        Date date1 = new Date();
        SpinnerDateModel sm1 =
        new SpinnerDateModel(date1,null,null,Calendar.HOUR_OF_DAY);
        jSpinner2 = new javax.swing.JSpinner(sm1);
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATE :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 50, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("From");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 32, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 24, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PickUp Time");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Drop Time");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PickUp Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Drop Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 90, 20));

        pic.setColumns(20);
        pic.setRows(5);
        jScrollPane1.setViewportView(pic);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        drp.setColumns(20);
        drp.setRows(5);
        jScrollPane2.setViewportView(drp);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 80, -1));

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, -1));

        jButton4.setText("Select Car");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 40, -1));

        ema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emaActionPerformed(evt);
            }
        });
        getContentPane().add(ema, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 128, -1));
        getContentPane().add(frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));
        getContentPane().add(to1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinner1,"HH-mm-ss a");
        jSpinner1.setEditor(de);
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 129, -1));

        JSpinner.DateEditor de1 = new JSpinner.DateEditor(jSpinner2,"HH-mm-ss a");
        jSpinner2.setEditor(de1);
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 129, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("FILL UP YOUR BOOKING DETAILS!!!");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\pratik rathod\\Downloads\\PHOTOS\\Dark Blue Background Wallpaper 1920x1080 Dark Blue Background.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

this.setVisible(false);
        new Customer(temp).setVisible(true); 


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
              String new_pid="";   
                 String pid2="b101";
              
              Date value = (Date) jSpinner1.getValue();
              value=(Timestamp)new Timestamp(value.getTime());
              
             Date value1 = (Date) jSpinner2.getValue();
              value1=(Timestamp)new Timestamp(value1.getTime());
             //  int nop1=Integer.parseInt(nop.getText());
               //sint noc1=Integer.parseInt(noc.getText());
               String pic1=pic.getText();
               String drp1=drp.getText();
              // String ema1=ema.getText();
               String p=null;
               String pp="pr";
             String insert1="select *from person;";
           //  String insert2="select distinct Pid person where email=?;";
             SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
             String aaa=dateFormat.format(frm.getDate());
             SimpleDateFormat dateFormat1=new SimpleDateFormat("yyyy-MM-dd");
             String ppp=dateFormat.format(to1.getDate());  
   Connection cn = null;
        try{ 
              
                  cn=LoginForm.guicon();
                  PreparedStatement pstmt;
                  
                  pstmt=cn.prepareStatement(insert1);
                   ResultSet rs=pstmt.executeQuery();
                   
          
                  while(rs.next())
                 {    
                     String mail=rs.getString("email");
                     
                     if(ema.getText().equals(mail))
                         { 
                             p = rs.getString("Pid");
                             System.out.println(p);
                             
                            
                         }
                         
               
                 }
                  String insert3="select *from booking1;";
                   pstmt=cn.prepareStatement(insert3);
                      ResultSet rs1=pstmt.executeQuery();
                   while(rs1.next())
                        {
                            pid2=rs1.getString("bid");
                        if(pid2.equals(""))
                        {
                          pid2="b101";
                          
                        }
                        else{
                            int new_str=Integer.parseInt(pid2.replaceAll("[\\D]", ""));
                            new_str+=1;
                            pid2="b"+new_str;
                            System.out.println(new_pid);
                        }
                        }
                  
                   
                   
                   
        String insert="INSERT INTO booking1 VALUES(?,?,?,?,?,?,?,?,?);";  
        pstmt=cn.prepareStatement(insert);
            pstmt.setString(1,pid2); 
            pstmt.setString(2,p);
            pstmt.setString(3,null);
            pstmt.setString(4,aaa);
            pstmt.setString(5,ppp);
            pstmt.setTimestamp(6, (Timestamp) value);
            pstmt.setTimestamp(7, (Timestamp) value1);
            pstmt.setString(8,pic1);
            pstmt.setString(9,drp1);
            int r=pstmt.executeUpdate();
        System.out.println("Rows affected: "+r);
            
        this.setVisible(false);
       // new SelectCar().setVisible(true); 
        SelectCar a=new SelectCar();
//          String insert5="INSERT INTO key1 VALUES(?,?,?);";  
//        pstmt=cn.prepareStatement(insert5); 
//        
//        pstmt.setString(1,pid2);
//            pstmt.setString(2,p);
//            pstmt.setString(3,pp);
//        int q=pstmt.executeUpdate();
//        System.out.println("Rows affected: "+q);
          this.setVisible(false);
        new SelectCar(pid2,temp).setVisible(true);
        
 }
        
        catch (SQLException ex) {
                 
                     
                       Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);  
        }  


    }//GEN-LAST:event_jButton4ActionPerformed

    private void emaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     // ema.setText("");
      //  from.setText("");
         // to.setText("");
//            nop.setText("");
//              noc.setText("");
              
                pic.setText("");
                  drp.setText("");
                  
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea drp;
    private javax.swing.JTextField ema;
    private com.toedter.calendar.JDateChooser frm;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea pic;
    private com.toedter.calendar.JDateChooser to1;
    // End of variables declaration//GEN-END:variables
}
