
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pratik rathod
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        
//        this.setUndecorated(true);
//        this.setAlwaysOnTop(true);
//        this.setResizable(false);
//        this.setVisible(true);
        initComponents();
//        Toolkit tk = Toolkit.getDefaultToolkit();
//        int xsize=(int)tk.getScreenSize().getWidth();
//        int ysize=(int)tk.getScreenSize().getWidth();
//        this.setSize(xsize,ysize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lutf = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lupf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        customer = new javax.swing.JRadioButton();
        admin = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(17, 17, 17));

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(51, 0, 0));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 382, 280, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 113, 177));
        jLabel1.setText("New User ?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 466, 100, -1));

        lutf.setBackground(new java.awt.Color(50, 50, 50));
        lutf.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lutf.setForeground(new java.awt.Color(255, 255, 255));
        lutf.setBorder(null);
        lutf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lutfActionPerformed(evt);
            }
        });
        jPanel1.add(lutf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 390, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 256, 390, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 138, 390, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 113, 177));
        jLabel3.setText("USERNAME / EMAIL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 150, -1));

        lupf.setBackground(new java.awt.Color(50, 50, 50));
        lupf.setForeground(new java.awt.Color(255, 255, 255));
        lupf.setBorder(null);
        jPanel1.add(lupf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 236, 390, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(53, 113, 177));
        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 196, 80, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Create An Account");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 498, 280, -1));

        customer.setBackground(new java.awt.Color(53, 113, 177));
        customer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customer.setForeground(new java.awt.Color(153, 153, 255));
        customer.setText("Customer");
        customer.setBorder(null);
        customer.setBorderPainted(true);
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        jPanel1.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 306, -1, 20));

        admin.setBackground(new java.awt.Color(53, 113, 177));
        admin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        admin.setForeground(new java.awt.Color(153, 153, 255));
        admin.setText("Admin");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel1.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 306, 70, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\pratik rathod\\Desktop\\os_vehicle_manager.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 24, 880, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lutfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lutfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lutfActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                 String nam=lutf.getText();
        String pass=lupf.getText();
        Connection cn=LoginForm.guicon();

        PreparedStatement pstmt = null;

        if(admin.isSelected()) {
            try{

                pstmt=cn.prepareStatement("Select *from login");

                ResultSet rs=pstmt.executeQuery();
                int flag=0;
                while(rs.next())
                {
                    String dbuser=rs.getString("username");
                    String dbpass=rs.getString("password");

                    if(lutf.getText().equals(dbuser) && lupf.getText().equals(dbpass))
                    {
                        JOptionPane.showMessageDialog(null,"You Have Been Logged In");
                        this.setVisible(false);
                        new Admin2().setVisible(true);
                        flag=1;

                    }

                }
                if(flag==0)
                {
                    JOptionPane.showMessageDialog(null,"Something Is Wrong");

                }

            }
            catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

                
                else if(customer.isSelected()) {
            try{

                Customer cus = new Customer();

                pstmt=cn.prepareStatement("Select * from cuslogin");

                ResultSet rs=pstmt.executeQuery();
                int flag=0;
                while(rs.next())
                {
                    String mail=rs.getString("email");
                    String dbuser=rs.getString("username");
                    String dbpass=rs.getString("password");

                    if(lutf.getText().equals(dbuser) || lutf.getText().equals(mail) && lupf.getText().equals(dbpass))
                    {
                        JOptionPane.showMessageDialog(null,"You Have Been Logged In");
                        this.setVisible(false);
                        new Customer(nam).setVisible(true);
                        flag=1;

                    }

                }
                if(flag==0)
                {
                    JOptionPane.showMessageDialog(null,"Something Is Wrong");
                }
            }
              catch (SQLException ex)
                 {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                  }
               
                }
                
                else{
                       JOptionPane.showMessageDialog(null,"PLEASE SELECT CATEGORY");
                    }
                
                
                
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
ButtonGroup group = new ButtonGroup();
group.add(customer);
group.add(admin);




    }//GEN-LAST:event_adminActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.setVisible(false);
        new FillDetailsCustomer().setVisible(true);




    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin;
    private javax.swing.JRadioButton customer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField lupf;
    private javax.swing.JTextField lutf;
    // End of variables declaration//GEN-END:variables
}
